import Head from 'next/head';
import Form from '../components/Form/Form';
import Body from '../components/Home/Body';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Connect</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Form />
      <Body />
      {/* Display number of users */}
    </div>
  );
}
